name: nav_view
description: A new Flutter plugin.
version: 0.0.1
author:
publish_to: none


environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.reemii.nav_view
        pluginClass: NavViewPlugin
      ios:
        pluginClass: NavViewPlugin
      macos:
        pluginClass: NavViewPlugin


